/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AdminRouteImport } from "./routes/_admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminUsersRouteImport } from "./routes/_admin/users";
import { Route as AdminPropertiesRouteImport } from "./routes/_admin/properties";
import { Route as AdminPaymentsRouteImport } from "./routes/_admin/payments";
import { Route as AdminNotificationsRouteImport } from "./routes/_admin/notifications";
import { Route as AdminMessagesRouteImport } from "./routes/_admin/messages";
import { Route as AdminMaintenanceRouteImport } from "./routes/_admin/maintenance";
import { Route as AdminLeasesRouteImport } from "./routes/_admin/leases";
import { Route as AdminDashboardRouteImport } from "./routes/_admin/dashboard";
import { Route as AdminIncidentsRouteImport } from "./routes/_admin/incidents";
import { Route as AdminReportsRouteImport } from "./routes/_admin/reports";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/_admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any);
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: "/properties",
  path: "/properties",
  getParentRoute: () => AdminRoute,
} as any);
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => AdminRoute,
} as any);
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => AdminRoute,
} as any);
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => AdminRoute,
} as any);
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: "/maintenance",
  path: "/maintenance",
  getParentRoute: () => AdminRoute,
} as any);
const AdminLeasesRoute = AdminLeasesRouteImport.update({
  id: "/leases",
  path: "/leases",
  getParentRoute: () => AdminRoute,
} as any);
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AdminRoute,
} as any);
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: "/incidents",
  path: "/incidents",
  getParentRoute: () => AdminRoute,
} as any);
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AdminRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/dashboard": typeof AdminDashboardRoute;
  "/incidents": typeof AdminIncidentsRoute;
  "/reports": typeof AdminReportsRoute;
  "/leases": typeof AdminLeasesRoute;
  "/maintenance": typeof AdminMaintenanceRoute;
  "/messages": typeof AdminMessagesRoute;
  "/notifications": typeof AdminNotificationsRoute;
  "/payments": typeof AdminPaymentsRoute;
  "/properties": typeof AdminPropertiesRoute;
  "/users": typeof AdminUsersRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/dashboard": typeof AdminDashboardRoute;
  "/incidents": typeof AdminIncidentsRoute;
  "/reports": typeof AdminReportsRoute;
  "/leases": typeof AdminLeasesRoute;
  "/maintenance": typeof AdminMaintenanceRoute;
  "/messages": typeof AdminMessagesRoute;
  "/notifications": typeof AdminNotificationsRoute;
  "/payments": typeof AdminPaymentsRoute;
  "/properties": typeof AdminPropertiesRoute;
  "/users": typeof AdminUsersRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_admin": typeof AdminRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_admin/dashboard": typeof AdminDashboardRoute;
  "/_admin/incidents": typeof AdminIncidentsRoute;
  "/_admin/reports": typeof AdminReportsRoute;
  "/_admin/leases": typeof AdminLeasesRoute;
  "/_admin/maintenance": typeof AdminMaintenanceRoute;
  "/_admin/messages": typeof AdminMessagesRoute;
  "/_admin/notifications": typeof AdminNotificationsRoute;
  "/_admin/payments": typeof AdminPaymentsRoute;
  "/_admin/properties": typeof AdminPropertiesRoute;
  "/_admin/users": typeof AdminUsersRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/dashboard"
    | "/incidents"
    | "/reports"
    | "/leases"
    | "/maintenance"
    | "/messages"
    | "/notifications"
    | "/payments"
    | "/properties"
    | "/users";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/dashboard"
    | "/incidents"
    | "/reports"
    | "/leases"
    | "/maintenance"
    | "/messages"
    | "/notifications"
    | "/payments"
    | "/properties"
    | "/users";
  id:
    | "__root__"
    | "/"
    | "/_admin"
    | "/login"
    | "/_admin/dashboard"
    | "/_admin/leases"
    | "/_admin/maintenance"
    | "/_admin/messages"
    | "/_admin/notifications"
    | "/_admin/payments"
    | "/_admin/properties"
    | "/_admin/users";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin": {
      id: "/_admin";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin/users": {
      id: "/_admin/users";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof AdminUsersRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/properties": {
      id: "/_admin/properties";
      path: "/properties";
      fullPath: "/properties";
      preLoaderRoute: typeof AdminPropertiesRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/payments": {
      id: "/_admin/payments";
      path: "/payments";
      fullPath: "/payments";
      preLoaderRoute: typeof AdminPaymentsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/notifications": {
      id: "/_admin/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof AdminNotificationsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/messages": {
      id: "/_admin/messages";
      path: "/messages";
      fullPath: "/messages";
      preLoaderRoute: typeof AdminMessagesRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/maintenance": {
      id: "/_admin/maintenance";
      path: "/maintenance";
      fullPath: "/maintenance";
      preLoaderRoute: typeof AdminMaintenanceRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/leases": {
      id: "/_admin/leases";
      path: "/leases";
      fullPath: "/leases";
      preLoaderRoute: typeof AdminLeasesRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/dashboard": {
      id: "/_admin/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AdminDashboardRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/incidents": {
      id: "/_admin/incidents";
      path: "/incidents";
      fullPath: "/incidents";
      preLoaderRoute: typeof AdminIncidentsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/_admin/reports": {
      id: "/_admin/reports";
      path: "/reports";
      fullPath: "/reports";
      preLoaderRoute: typeof AdminReportsRouteImport;
      parentRoute: typeof AdminRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute;
  AdminIncidentsRoute: typeof AdminIncidentsRoute;
  AdminReportsRoute: typeof AdminReportsRoute;
  AdminLeasesRoute: typeof AdminLeasesRoute;
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute;
  AdminMessagesRoute: typeof AdminMessagesRoute;
  AdminNotificationsRoute: typeof AdminNotificationsRoute;
  AdminPaymentsRoute: typeof AdminPaymentsRoute;
  AdminPropertiesRoute: typeof AdminPropertiesRoute;
  AdminUsersRoute: typeof AdminUsersRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminLeasesRoute: AdminLeasesRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminUsersRoute: AdminUsersRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
